### ISSUE TITLE
Moar zturn stuff 

### ISSUE THREAD

**Issue by unkier** [q3k/zturn-stuff#6]
Hi Serge. I want to say thank you, for sharing this very helpful files. Also, I made a buildroot version with z-turn support(including uboot and kernel).  Maybe you will find it useful and will add a link to my repo to your handy readme file )

So just:

git clone https://github.com/unkier/buildroot-zturn.git
cd buildroot-zturn
make zynq_zturn_defconfig
make

Thanks again.

**Comment by q3k** [comment]
Very nice! This will make things much simpler for me, too.
